only_if: $CIRRUS_BRANCH == $CIRRUS_DEFAULT_BRANCH || $CIRRUS_BRANCH !=~ 'pull/.*'
task:
  name: Windows build
  windows_container:
    image: cirrusci/windowsservercore:2019
  choco_cache:
    # should be under %CIRRUS_WORKING_DIR%
    folder: .chocolatey
  matrix:
    # add more JDK versions here
    - name: Cirrus - JDK17
      env:
        OPENJDK_VERSION: "17.0.0"
        OPENJDK_PATH: "jdk-17"
  env:
    # disable ANSI output for picocli (may affect tests)
    NO_COLOR: "1"
    # https://stackoverflow.com/questions/42024619/maven-build-gets-connection-reset-when-downloading-artifacts
    MAVEN_OPTS: "-Dhttp.keepAlive=false \
      -Dmaven.repo.local=%CIRRUS_WORKING_DIR%/.m2 \
      -Dmaven.wagon.http.retryHandler.count=3"
  install_script:
    - choco config set cacheLocation %CIRRUS_WORKING_DIR%/.chocolatey
    - choco upgrade -y chocolatey
    - choco install -y --no-progress ant
    - choco install -y --no-progress openjdk --version %OPENJDK_VERSION%
    - dif C:\ProgramData\chocolatey\
    # - choco install -y --no-progress xsltproc
    # - choco install -y --no-progress xmlstarlet
  version_script:
    - set
    - ant -version
    - java --version
    - ./mvnw --version
    # - xsltproc --version
    # - xml --version
  maven_cache:
    # should be under %CIRRUS_WORKING_DIR%
    folder: .m2
    include:
      - .mvn/wrapper
  clone_script:
    - git config core.autocrlf
    - git clone --recursive
          https://x-access-token:%CIRRUS_REPO_CLONE_TOKEN%@github.com/%CIRRUS_REPO_FULL_NAME%.git
          %CIRRUS_WORKING_DIR%/ci
    - cd ci
    - cmd /c "if defined CIRRUS_PR (git fetch origin pull/%CIRRUS_PR%/head:pull/%CIRRUS_PR%)"
    - git reset --hard %CIRRUS_CHANGE_IN_REPO%
  sevntu_script:
    - cd ci
    - .ci/validation.cmd sevntu
  verify_without_checkstyle_script:
    - cd ci
    - .ci/validation.cmd verify_without_checkstyle
  site_without_verify_script:
    - cd ci
    - .ci/validation.cmd site_without_verify
