task:
  name: Windows build
  windows_container:
    image: cirrusci/windowsservercore:2019
  clone_script:
    - git config core.autocrlf
    - git clone --recursive
          https://x-access-token:%CIRRUS_REPO_CLONE_TOKEN%@github.com/%CIRRUS_REPO_FULL_NAME%.git
          %CIRRUS_WORKING_DIR%/ci
    - cd ci
    - git fetch origin pull/%CIRRUS_PR%/head:pull/%CIRRUS_PR%
    - git reset --hard %CIRRUS_CHANGE_IN_REPO%
  choco_cache:
    # should be under %CIRRUS_WORKING_DIR%
    folder: .chocolatey
  maven_cache:
    # should be under %CIRRUS_WORKING_DIR%
    folder: .m2
  matrix:
    - name: Cirrus - JDK11
      env:
        OPENJDK_VERSION: "11.0.2.01"
        OPENJDK_PATH: "jdk-11.0.2"
    - name: Cirrus - JDK14
      env:
        OPENJDK_VERSION: "14.0.2"
        OPENJDK_PATH: "jdk-14.0.2"
    - name: Cirrus - JDK15
      env:
        OPENJDK_VERSION: "15.0.0"
        OPENJDK_PATH: "jdk-15"
  env:
    # disable ANSI output for picocli (may affect tests)
    NO_COLOR: "1"
    # https://stackoverflow.com/questions/42024619/maven-build-gets-connection-reset-when-downloading-artifacts
    MAVEN_OPTS:
      - -Dhttp.keepAlive=false
        -Dmaven.repo.local=%CIRRUS_WORKING_DIR%/.m2
        -Dmaven.wagon.http.retryHandler.count=3
        -Dmaven.wagon.http.pool=false
    MAVEN_VERSION: "3.6.3"
    PATH: "%PATH%;C:/Program Files/OpenJDK/%OPENJDK_PATH%/bin;\
      C:/ProgramData/chocolatey/lib/maven/apache-maven-%MAVEN_VERSION%/bin;\
      C:/ProgramData/chocolatey/bin"
  install_script:
    - choco config set cacheLocation %CIRRUS_WORKING_DIR%/.chocolatey
    - choco upgrade -y chocolatey
    - choco install -y ant
    - choco install -y maven --version %MAVEN_VERSION%
    - choco install -y openjdk --version %OPENJDK_VERSION%
    - choco install -y xsltproc
    - choco install -y xmlstarlet
  version_script:
    - set
    - ant -version
    - java --version
    - mvn --version
    - xsltproc --version
    - xml --version
  test_script:
    - .ci/validation.cmd verify_without_checkstyle
