---
kind: pipeline
type: docker
name: checkstyle_spotbugs-pmd

steps:
- name: checkstyle-and-sevntu
  image: maven:3.8.4-openjdk-11
  commands:
  - ./.ci/validation.sh checkstyle-and-sevntu
  - ./.ci/validation.sh git-diff

- name: spotbugs-and-pmd
  image: maven:3.8.4-openjdk-11
  commands:
  - ./.ci/validation.sh spotbugs-and-pmd
  - ./.ci/validation.sh git-diff

---
kind: pipeline
type: docker
name: site

steps:
- name: site
  image: maven:3.8.4-openjdk-11
  commands:
  - ./.ci/validation.sh site
  - ./.ci/validation.sh git-diff


---
kind: pipeline
type: docker
name: dry-run_run-all

steps:
- name: release-dry-run
  image: maven:3.8.4-openjdk-11
  commands:
  - ./.ci/validation.sh release-dry-run
  - ./.ci/validation.sh git-diff

- name: assembly-run-all-jar
  image: maven:3.8.4-openjdk-11
  commands:
  - ./.ci/validation.sh assembly-run-all-jar
  - ./.ci/validation.sh git-diff

---
kind: pipeline
type: docker
name: releasenotes

steps:
- name: releasenotes-gen
  image: maven:3.8.4-openjdk-11
  environment:
    READ_ONLY_TOKEN:
      from_secret: READ_ONLY_TOKEN
  commands:
  - export PULL_REQUEST=$DRONE_PULL_REQUEST && ./.ci/releasenotes-gen.sh
  - ./.ci/validation.sh git-diff

---
kind: pipeline
type: docker
name: non-mvn_javac

steps:
- name: check-chmod
  image: maven:3.8.4-openjdk-11
  commands:
  - ./.ci/checkchmod.sh

- name: check-since-version
  image: maven:3.8.4-openjdk-11
  commands:
  - ./.ci/validation.sh check-since-version

- name: javac11
  image: maven:3.8.4-openjdk-11
  commands:
  - ./.ci/validation.sh javac11

- name: javac14
  image: maven:3.6.3-adoptopenjdk-14
  commands:
  - ./.ci/validation.sh javac14

- name: javac15
  image: maven:3.6.3-adoptopenjdk-15
  commands:
  - ./.ci/validation.sh javac15

- name: javac16
  image: maven:3.8.1-openjdk-16
  commands:
  - ./.ci/validation.sh javac16

- name: javac17
  image: maven:3.8.4-openjdk-17
  commands:
  - ./.ci/validation.sh javac17

---
kind: pipeline
type: docker
name: assembly-site_sbe

steps:
- name: jdk14-assembly-site
  image: maven:3.6.3-jdk-14

  commands:
  - ./.ci/validation.sh jdk14-assembly-site
  - ./.ci/validation.sh git-diff

- name: assembly/site with OpenJDK11
  image: maven:3.8.4-openjdk-11

  commands:
  - "mvn -e --no-transfer-progress package -Passembly && \
     mvn -e --no-transfer-progress site -Dlinkcheck.skip=true"
  - ./.ci/validation.sh git-diff

- name: no-error-test-sbe
  image: maven:3.8.4-openjdk-11

  commands:
  - ./.ci/validation.sh no-error-test-sbe
  - ./.ci/validation.sh git-diff
