---
kind: pipeline
name: checkstyle_spotbugs-pmd

volumes:
- name: m2-cache
  temp: {}

steps:
- name: restore-cache
  image: &default-image maven:3.8.4-openjdk-11
  failure: ignore
  volumes:
  - name: m2-cache
    path: /.m2
  commands:
  - ./.ci/drone-io.sh restore-maven-cache

- name: checkstyle-and-sevntu
  image: *default-image
  environment:
    MAVEN_OPTS: "-Dmaven.repo.local=/.m2"
  volumes:
  - name: m2-cache
    path: /.m2
  commands:
  - ./.ci/validation.sh checkstyle-and-sevntu

- name: spotbugs-and-pmd
  image: *default-image
  environment:
    MAVEN_OPTS: "-Dmaven.repo.local=/.m2"
  volumes:
  - name: m2-cache
    path: /.m2
  commands:
  - ./.ci/validation.sh spotbugs-and-pmd

---
kind: pipeline
name: site

volumes:
- name: m2-cache
  temp: {}

steps:
- name: restore-cache
  image: &default-image maven:3.8.4-openjdk-11
  failure: ignore
  volumes:
  - name: m2-cache
    path: /.m2
  commands:
  - ./.ci/drone-io.sh restore-maven-cache

- name: site
  image: *default-image
  environment:
    MAVEN_OPTS: "-Dmaven.repo.local=/.m2"
  volumes:
  - name: m2-cache
    path: /.m2
  commands:
  - ./.ci/validation.sh site


---
kind: pipeline
name: dry-run_run-all

volumes:
- name: m2-cache
  temp: {}

steps:
- name: restore-cache
  image: &default-image maven:3.8.4-openjdk-11
  failure: ignore
  volumes:
  - name: m2-cache
    path: /.m2
  commands:
  - ./.ci/drone-io.sh restore-maven-cache

- name: release-dry-run
  image: *default-image
  environment:
    MAVEN_OPTS: "-Dmaven.repo.local=/.m2"
  volumes:
  - name: m2-cache
    path: /.m2
  commands:
  - ./.ci/validation.sh release-dry-run

- name: assembly-run-all-jar
  image: *default-image
  environment:
    MAVEN_OPTS: "-Dmaven.repo.local=/.m2"
  volumes:
  - name: m2-cache
    path: /.m2
  commands:
  - ./.ci/validation.sh assembly-run-all-jar

---
kind: pipeline
name: releasenotes

volumes:
- name: m2-cache
  temp: {}

steps:
- name: restore-cache
  image: &default-image maven:3.8.4-openjdk-11
  failure: ignore
  volumes:
  - name: m2-cache
    path: /.m2
  commands:
  - ./.ci/drone-io.sh restore-maven-cache

- name: releasenotes-gen
  image: *default-image
  environment:
    READ_ONLY_TOKEN:
      from_secret: READ_ONLY_TOKEN
    MAVEN_OPTS: "-Dmaven.repo.local=/.m2"
  volumes:
  - name: m2-cache
    path: /.m2
  commands:
  - export PULL_REQUEST=$DRONE_PULL_REQUEST && ./.ci/releasenotes-gen.sh

---
kind: pipeline
name: non-mvn_javac

steps:
- name: check-chmod
  image: &default-image maven:3.8.4-openjdk-11
  commands:
  - ./.ci/checkchmod.sh

- name: check-since-version
  image: *default-image
  commands:
  - ./.ci/validation.sh check-since-version

- name: javac11
  image: *default-image
  commands:
  - ./.ci/validation.sh javac11

- name: javac14
  image: maven:3.6.3-adoptopenjdk-14
  commands:
  - ./.ci/validation.sh javac14

- name: javac15
  image: maven:3.6.3-adoptopenjdk-15
  commands:
  - ./.ci/validation.sh javac15

- name: javac16
  image: maven:3.8.1-openjdk-16
  commands:
  - ./.ci/validation.sh javac16

- name: javac17
  image: maven:3.8.4-openjdk-17
  commands:
  - ./.ci/validation.sh javac17

---
kind: pipeline
name: assembly-site_sbe

volumes:
- name: m2-cache
  temp: {}

steps:
- name: restore-cache
  image: &default-image maven:3.8.4-openjdk-11
  failure: ignore
  volumes:
  - name: m2-cache
    path: /.m2
  commands:
  - ./.ci/drone-io.sh restore-maven-cache

- name: jdk14-assembly-site
  image: maven:3.6.3-jdk-14
  environment:
    MAVEN_OPTS: "-Dmaven.repo.local=/.m2"
  volumes:
  - name: m2-cache
    path: /.m2
  commands:
  - ./.ci/validation.sh jdk14-assembly-site

- name: assembly/site with OpenJDK11
  image: *default-image
  environment:
    MAVEN_OPTS: "-Dmaven.repo.local=/.m2"
  volumes:
  - name: m2-cache
    path: /.m2
  commands:
  - "mvn -e --no-transfer-progress package -Passembly && \
     mvn -e --no-transfer-progress site -Dlinkcheck.skip=true"

- name: no-error-test-sbe
  image: *default-image
  environment:
    MAVEN_OPTS: "-Dmaven.repo.local=/.m2"
  volumes:
  - name: m2-cache
    path: /.m2
  commands:
  - ./.ci/validation.sh no-error-test-sbe
