-- CHECKSTYLE OFF
	SELECT COUNT(1) FROM filters;

-- CHECKSTYLE ON
	SELECT COUNT(1) FROM checks;

	SELECT COUNT(1) FROM tests; -- CHECKSTYLE DEFAULT

-- CHECKSTYLE DEFAULT
	SELECT COUNT(1) FROM checks;
