#<module name="Checker">
#  <property name="fileExtensions" value="properties"/>
#
#  <module name="UniqueProperties"/>
#  <module name="SuppressWithPlainTextCommentFilter"/>
#
#</module>

# xdoc section - start
# // CHECKSTYLE:OFF
keyB=value1 # // filtered violation 'Duplicated property 'keyB' (2 occurrence(s)).'
keyB=value2
# // CHECKSTYLE:ON
# // violation below 'Duplicated property 'keyC' (2 occurrence(s)).'
keyC=value4
keyC=value5
# xdoc section - end
