steps:
  - label: ":checkstyle: checkstyle"
    command: "./.ci/validation.sh checkstyle"
    plugins:
      - docker#v5.0.0:
          image: "maven:3.9-eclipse-temurin-21"
          volumes:
            - "/tmp/buildkite-maven-cache:/root/.m2"

  - label: ":checkstyle: sevntu"
    command: "./.ci/validation.sh sevntu"
    plugins:
      - docker#v5.0.0:
          image: "maven:3.9-eclipse-temurin-21"
          volumes:
            - "/tmp/buildkite-maven-cache:/root/.m2"

  - label: ":clean: spotless"
    command: "./.ci/validation.sh spotless"
    plugins:
      - docker#v5.0.0:
          image: "maven:3.9-eclipse-temurin-21"
          volumes:
            - "/tmp/buildkite-maven-cache:/root/.m2"
