package com.puppycrawl.tools.checkstyle.checks.lineending; // violation 'Expected line ending for file is CRLF, but LF is detected.'
                                                           // violation 'Expected line ending for file is CRLF, but LF is detected.'
public class InputLineEndingCrlfExpected2 {                // violation 'Expected line ending for file is CRLF, but LF is detected.'
    public void method() {                                 // violation 'Expected line ending for file is CRLF, but LF is detected.'
        int a = 1;                                         // violation 'Expected line ending for file is CRLF, but LF is detected.'
    }                                                      // violation 'Expected line ending for file is CRLF, but LF is detected.'
}                                                          // violation 'Expected line ending for file is CRLF, but LF is detected.'
