name: Codenarc-Analysis

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  codenarc-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install groovy
        run: sudo apt install groovy
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Analysis
        run: ./.ci/codenarc.sh
