#############################################################################
# GitHub Action to Run Maven Release Prepare.
#
#############################################################################
name: "R: Maven Release Prepare"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Target Version without (-SNAPSHOT)'
        required: true
jobs:
  prepare:
    name: Prepare Release ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
      - name: Download xmlstarlet
        run: |
          sudo apt-get install xmlstarlet
      - name: Commit and Push Credentials
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Run Shell Script
        run: |
          ./.ci/maven-prepare.sh ${{ github.event.inputs.version }}
