name: Pitest

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pitest:
    strategy:
      matrix:
        profile:
          - pitest-annotation
          - pitest-ant
          - pitest-api
          - pitest-blocks
          - pitest-coding-1
          - pitest-coding-2
          - pitest-coding-require-this-check
          - pitest-common
          - pitest-common-2
          - pitest-design
          - pitest-filters
          - pitest-header
          - pitest-imports
          - pitest-indentation
          - pitest-javadoc
          - pitest-main
          - pitest-metrics
          - pitest-misc
          - pitest-modifier
          - pitest-naming
          - pitest-packagenamesloader
          - pitest-regexp
          - pitest-sizes
          - pitest-tree-walker
          - pitest-utils
          - pitest-whitespace
          - pitest-xpath
          - pitest-java-ast-visitor
        # GUI package needs better test coverage before adding to execution.
        # - pitest-gui
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install groovy
        run: sudo apt install groovy
      - name: Setup local maven cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: checkstyle-maven-cache-${{ hashFiles('**/pom.xml') }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate ${{ matrix.profile }} report
        run: |
          mvn -e --no-transfer-progress -P"${{ matrix.profile }}" clean test-compile \
          org.pitest:pitest-maven:mutationCoverage
      - name: Check ${{ matrix.profile }} report
        run: |
          groovy ./.ci/pitest-survival-check-xml.groovy ${{ matrix.profile }}
      - name: Stage results
        if: failure() || github.ref == 'refs/heads/master'
        run: |
          mkdir staging && cp -r target/pit-reports/ staging
      - name: Archive code coverage results
        if: failure() || github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.profile }}-coverage-report
          path: staging
          retention-days: 7
