#############################################################################
# GitHub Action to Publish Tweet of release notes.
#
#############################################################################
name: "R: Publish Tweet"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Target Version without (-SNAPSHOT)'
        required: true
jobs:
  publish:
    name: Publish releasenotes tweet for ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Shell Script
        run: |
          ./.ci/tweet-releasenotes.sh ${{ github.event.inputs.version }}
        env:
          GITHUB_READ_ONLY_TOKEN : ${{ secrets.READ_ONLY_TOKEN_GITHUB }}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
