#####################################################################################
# GitHub Action to run link checks.
#
# Workflow starts when:
# 1) push on master branch
#
#####################################################################################
name: "Check no broken links"

on:
  push:
    branches: [ master ]

jobs:
  check_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Download checkstyle
        uses: actions/checkout@v3

      - name: Check links
        run: ./.ci/run-link-check-plugin.sh
