#############################################################################
# GitHub Action to Push Release Notes.
#
#############################################################################
name: "R: Push Release Notes"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Target Version without (-SNAPSHOT)'
        required: true
jobs:
  releasenotes:
    name: Push releasenotes ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
      - name: Download xmlstarlet
        run: |
          sudo apt-get install xmlstarlet
      - name: Run Shell Script
        run: |
          ./.ci/update-releasenotesxml.sh ${{ github.event.inputs.version }}
      - name: Commit and Push
        run: |
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
            git add . && git commit -m "doc: release notes for ${{ github.event.inputs.version }}"
            git push origin master
