/*
JavaNCSS
methodMaximum = (default)50
classMaximum = 80
fileMaximum = (default)2000
recordMaximum = (default)150


*/

//non-compiled with javac: Compilable with Java14
package com.puppycrawl.tools.checkstyle.checks.metrics.javancss;

public class InputJavaNCSSRecordsMax {// violation 'NCSS for this class is 152 (max allowed is 80)'
    record MyRecord() { // violation 'NCSS for this record is 151 (max allowed is 150)'
        static int myRecordField1 = 0;
        static int myRecordField2 = 0;
        static int myRecordField3 = 0;
        static int myRecordField4 = 0;
        static int myRecordField5 = 0;
        static int myRecordField6 = 0;
        static int myRecordField7 = 0;
        static int myRecordField8 = 0;
        static int myRecordField9 = 0;
        static int myRecordField10 = 0;
        static int myRecordField11 = 0;
        static int myRecordField12 = 0;
        static int myRecordField13 = 0;
        static int myRecordField14 = 0;
        static int myRecordField15 = 0;
        static int myRecordField16 = 0;
        static int myRecordField17 = 0;
        static int myRecordField18 = 0;
        static int myRecordField19 = 0;
        static int myRecordField20 = 0;
        static int myRecordField21 = 0;
        static int myRecordField22 = 0;
        static int myRecordField23 = 0;
        static int myRecordField24 = 0;
        static int myRecordField25 = 0;
        static int myRecordField26 = 0;
        static int myRecordField27 = 0;
        static int myRecordField28 = 0;
        static int myRecordField29 = 0;
        static int myRecordField30 = 0;
        static int myRecordField31 = 0;
        static int myRecordField32 = 0;
        static int myRecordField33 = 0;
        static int myRecordField34 = 0;
        static int myRecordField35 = 0;
        static int myRecordField36 = 0;
        static int myRecordField37 = 0;
        static int myRecordField38 = 0;
        static int myRecordField39 = 0;
        static int myRecordField40 = 0;
        static int myRecordField41 = 0;
        static int myRecordField42 = 0;
        static int myRecordField43 = 0;
        static int myRecordField44 = 0;
        static int myRecordField45 = 0;
        static int myRecordField46 = 0;
        static int myRecordField47 = 0;
        static int myRecordField48 = 0;
        static int myRecordField49 = 0;
        static int myRecordField50 = 0;
        static int myRecordField51 = 0;
        static int myRecordField52 = 0;
        static int myRecordField53 = 0;
        static int myRecordField54 = 0;
        static int myRecordField55 = 0;
        static int myRecordField56 = 0;
        static int myRecordField57 = 0;
        static int myRecordField58 = 0;
        static int myRecordField59 = 0;
        static int myRecordField60 = 0;
        static int myRecordField61 = 0;
        static int myRecordField62 = 0;
        static int myRecordField63 = 0;
        static int myRecordField64 = 0;
        static int myRecordField65 = 0;
        static int myRecordField66 = 0;
        static int myRecordField67 = 0;
        static int myRecordField68 = 0;
        static int myRecordField69 = 0;
        static int myRecordField70 = 0;
        static int myRecordField71 = 0;
        static int myRecordField72 = 0;
        static int myRecordField73 = 0;
        static int myRecordField74 = 0;
        static int myRecordField75 = 0;
        static int myRecordField76 = 0;
        static int myRecordField77 = 0;
        static int myRecordField78 = 0;
        static int myRecordField79 = 0;
        static int myRecordField80 = 0;
        static int myRecordField81 = 0;
        static int myRecordField82 = 0;
        static int myRecordField83 = 0;
        static int myRecordField84 = 0;
        static int myRecordField85 = 0;
        static int myRecordField86 = 0;
        static int myRecordField87 = 0;
        static int myRecordField88 = 0;
        static int myRecordField89 = 0;
        static int myRecordField90 = 0;
        static int myRecordField91 = 0;
        static int myRecordField92 = 0;
        static int myRecordField93 = 0;
        static int myRecordField94 = 0;
        static int myRecordField95 = 0;
        static int myRecordField96 = 0;
        static int myRecordField97 = 0;
        static int myRecordField98 = 0;
        static int myRecordField99 = 0;
        static int myRecordField100 = 0;
        static int myRecordField101 = 0;
        static int myRecordField102 = 0;
        static int myRecordField103 = 0;
        static int myRecordField104 = 0;
        static int myRecordField105 = 0;
        static int myRecordField106 = 0;
        static int myRecordField107 = 0;
        static int myRecordField108 = 0;
        static int myRecordField109 = 0;
        static int myRecordField110 = 0;
        static int myRecordField111 = 0;
        static int myRecordField112 = 0;
        static int myRecordField113 = 0;
        static int myRecordField114 = 0;
        static int myRecordField115 = 0;
        static int myRecordField116 = 0;
        static int myRecordField117 = 0;
        static int myRecordField118 = 0;
        static int myRecordField119 = 0;
        static int myRecordField120 = 0;
        static int myRecordField121 = 0;
        static int myRecordField122 = 0;
        static int myRecordField123 = 0;
        static int myRecordField124 = 0;
        static int myRecordField125 = 0;
        static int myRecordField126 = 0;
        static int myRecordField127 = 0;
        static int myRecordField128 = 0;
        static int myRecordField129 = 0;
        static int myRecordField130 = 0;
        static int myRecordField131 = 0;
        static int myRecordField132 = 0;
        static int myRecordField133 = 0;
        static int myRecordField134 = 0;
        static int myRecordField135 = 0;
        static int myRecordField136 = 0;
        static int myRecordField137 = 0;
        static int myRecordField138 = 0;
        static int myRecordField139 = 0;
        static int myRecordField140 = 0;
        static int myRecordField141 = 0;
        static int myRecordField142 = 0;
        static int myRecordField143 = 0;
        static int myRecordField144 = 0;
        static int myRecordField145 = 0;
        static int myRecordField146 = 0;
        static int myRecordField147 = 0;
        static int myRecordField148 = 0;
        static int myRecordField149 = 0;
        static int myRecordField150 = 0;
    }
}
