name: antlr4 project CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: clean verify
        run: mvn -e --no-transfer-progress clean verify

      - name: spotbugs
        run: mvn -e --no-transfer-progress clean test-compile spotbugs:check

      - name: pmd
        run: mvn -e --no-transfer-progress clean test-compile pmd:check

      - name: ant run
        run: mvn -e --no-transfer-progress clean compile antrun:run@ant-phase-verify

      - name: checkstyle and sevntu
        run: ./.ci/travis/travis.sh checkstyle-and-sevntu

      - name: spellchecker
        run: ./.ci/test-spelling-unknown-words.sh
