#############################################################################
# GitHub Action to Copy Site to SourceForge.
#
#############################################################################
name: "R: Copy Site to SourceForge"
on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release Version without (-SNAPSHOT)'
        required: true
jobs:
  copy-site:
    name: Copy site to sourceforge for ${{ github.event.inputs.release-version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          eval `ssh-agent -s`
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/private_sourceforge_key
          chmod 400 ~/.ssh/private_sourceforge_key
          ssh-add ~/.ssh/private_sourceforge_key
          ssh-keyscan -t ed25519 shell.sourceforge.net >> ~/.ssh/known_hosts

      - name: Run Shell Script
        env:
          SF_USER: ${{ secrets.SF_USER }}
        run: |
          ./.ci/copy-site-to-sourceforge.sh ${{ github.event.inputs.release-version }}
