#############################################################################
# GitHub Action to Run Maven Release Perform.
#
#############################################################################
name: "R: Maven Release Perform"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Target Version without (-SNAPSHOT)'
        required: true
  workflow_call:
    inputs:
      version:
        type: string
        required: true


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  perform:
    name: Release perform {{ inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master
      - name: Setup local maven cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: checkstyle-maven-cache-${{ hashFiles('**/pom.xml') }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          server-id: sonatype-nexus-staging
          server-username: SONATYPE_USER # env variable for username
          server-password: SONATYPE_PWD # env variable for token
          gpg-private-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: GPG_PASSPHRASE # env variable for GPG private key passphrase
      - name: Download xmlstarlet
        run: |
          sudo apt-get install xmlstarlet
      - name: Run Shell Script
        env:
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_PWD: ${{ secrets.SONATYPE_PWD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          cat ~/.m2/settings.xml
          ./.ci/maven-release-perform.sh ${{ inputs.version }}
