#############################################################################
# GitHub Action to Publish Release Notes on Twitter.
#
#############################################################################
name: "R: Publish Release Notes on Twitter"
run-name: "R: Publish Release Notes on Twitter ${{ inputs.version }}"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Target Version without (-SNAPSHOT)'
        required: true
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      concurrency-group:
        type: string
        required: true

concurrency:
  group: ${{ github.workflow }}
    -${{ github.event.pull_request.number || github.ref }}-${{ inputs.concurrency-group }}
  cancel-in-progress: true

jobs:
  publish-releasenotes-twitter:
    name: Publish Release Notes on Twitter ${{ inputs.version }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup local maven cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: checkstyle-maven-cache-${{ hashFiles('**/pom.xml') }}
      - name: Run Shell Script
        env:
          GITHUB_READ_ONLY_TOKEN: ${{ secrets.READ_ONLY_TOKEN_GITHUB }}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: |
          ./.ci/release-publish-releasenotes-twitter.sh ${{ inputs.version }}
