#####################################################################################
# GitHub Action to run checkstyle with:
#
#  target java file URL to print its AST
#
# Output is printed in console terminal
#
#####################################################################################
name: Run-Checkstyle-Ast-Print

on:
  workflow_dispatch:
    inputs:
      java-source-url:
        description: 'url to java source'
        required: true

concurrency:
  group: ${{ github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    if: github.repository == 'checkstyle/checkstyle'
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - uses: robinraju/release-downloader@v1
        with:
          repository: 'checkstyle/checkstyle'
          latest: true
          fileName: 'checkstyle-*.*.*-all.jar'

      - name: Download target java source
        run: |
            curl --fail-with-body -X GET "${{ inputs.java-source-url }}" \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -o "Test.java"

      - name: Run checkstyle AST printing
        run: |
            pwd
            ls -la
            echo "Content of Test.java:"
            cat -n Test.java
            echo ""
            JAR_NAME=$(find . -name "*-all.jar")
            echo "Executing: java -jar ""$JAR_NAME"" -T Test.java"
            java -jar "$JAR_NAME" -T Test.java
