name: "Deploy latest website"

env:
  AWS_REGION: "us-east-2"
  AWS_BUCKET_NAME: "checkstyle-diff-reports"

on:
  workflow_dispatch: null

permissions:
  contents: read

concurrency:
  group: deploy-latest-site
  cancel-in-progress: true

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup local maven cache
        uses: actions/cache/restore@v6
        with:
          path: ~/.m2/repository
          key: checkstyle-maven-cache-${{ hashFiles('**/pom.xml') }}

      - name: Set up JDK
        uses: actions/setup-java@v5.7.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Generate site
        run: |
          ./.ci/site-latest.sh generate-site

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Publish site to AWS S3
        run: |
          ./.ci/site-latest.sh publish-site
