#####################################################################################
# GitHub Action to generate Checkstyle site.
#
# Workflow starts when:
# 1) issue comment - created, edited
#
# Requirements:
# 1) secrets.AWS_ACCESS_KEY_ID - access key for AWS S3 service user
# 2) secrets.AWS_SECRET_ACCESS_KEY - security access key for AWS S3 service user
#
# If you need to change bucket name or region, change AWS_REGION and AWS_BUCKET_NAME variables.
# For another bucket, you will need to change the secrets.
#####################################################################################
name: "Site"

env:
  AWS_REGION: "us-east-2"
  AWS_BUCKET_NAME: "checkstyle-diff-reports"
  PR_NUMBER: >-
    ${{
      inputs.pr-number
      || github.event.issue.number
    }}

on:
  issue_comment:
    types: [ created, edited ]
  workflow_dispatch:
    inputs:
      pr-number:
        description: 'PR number'
        required: true
        type: string

permissions:
  contents: read
  pull-requests: write
  actions: read

concurrency:
  group: >-
    ${{ github.workflow }}-${{
      inputs.pr-number
      || github.event.issue.number
      || github.ref
    }}
  cancel-in-progress: false

jobs:
  site:
    if: github.event.comment.body == 'GitHub, generate web site'
          || github.event.comment.body == 'GitHub, generate website'
          || github.event.comment.body == 'GitHub, generate site'
          || inputs.pr-number != ''
    runs-on: ubuntu-latest
    outputs:
      commit_sha: ${{ steps.pr_info.outputs.commit_sha }}
    steps:
      - name: React to comment
        if: github.event_name == 'issue_comment'
        uses: actions/github-script@v9
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: 'rocket'
            })

      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          repository: checkstyle/checkstyle

      - name: Getting PR info
        id: pr_info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ env.PR_NUMBER }}
        run: |
          ./.ci/site.sh get-pr-info

      - name: Download checkstyle for PR
        uses: actions/checkout@v7
        with:
          ref: refs/pull/${{ env.PR_NUMBER }}/head
          path: .ci-temp/checkstyle
          fetch-depth: 0

      - name: Setup local maven cache
        uses: actions/cache/restore@v6
        with:
          path: ~/.m2/repository
          key: checkstyle-maven-cache-${{ hashFiles('**/pom.xml') }}

      - name: Set up JDK
        uses: actions/setup-java@v5.7.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Generate site
        run: |
          ./.ci/site.sh generate-site

      - name: Upload generated site
        uses: actions/upload-artifact@v7
        with:
          name: checkstyle-site
          path: .ci-temp/checkstyle/target/site
          if-no-files-found: error
          retention-days: 1

  publish_site:
    runs-on: ubuntu-latest
    needs: site
    outputs:
      message: ${{ steps.publish.outputs.message }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          repository: checkstyle/checkstyle

      - name: Download generated site
        uses: actions/download-artifact@v8
        with:
          name: checkstyle-site
          path: .ci-temp/checkstyle/target/site

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Publish site to AWS S3
        id: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_SHA: ${{ needs.site.outputs.commit_sha }}
          PR_NUMBER: ${{ env.PR_NUMBER }}
          AWS_BUCKET_NAME: ${{ env.AWS_BUCKET_NAME }}
          AWS_REGION: ${{ env.AWS_REGION }}
        run: |
          ./.ci/site.sh publish-site

  send_message:
    runs-on: ubuntu-latest
    needs: [ site, publish_site ]
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          repository: checkstyle/checkstyle

      - name: Build PR comment message
        if: always()
        env:
          MSG: ${{ needs.publish_site.outputs.message }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          FAILURE_PREFIX: "Site generation"
        run: ./.ci/build-pr-comment.sh

      - name: Export PR comment message
        id: out
        if: always()
        run: |
          ./.ci/append-to-github-output.sh "message" "$(cat .ci-temp/message)"

      - name: Comment PR
        if: always()
        uses: peter-evans/create-or-update-comment@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          issue-number: ${{ env.PR_NUMBER }}
          body: ${{ steps.out.outputs.message }}
