name: SonarQube

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check:
    strategy:
      fail-fast: true

    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Checkout
        uses: actions/checkout@v3

      - name: Execute sonar script
        env:
          MAVEN_OPTS: "-Xmx4g"
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./.ci/validation.sh sonarqube
