##
# GitHub Action to Update GitHub Milestone and Upload Jar.
#
#############################################################################
name: "GitHub Milestone and Upload Jar"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Target Version without (-SNAPSHOT)'
        required: true
jobs:
  github:
    name: Update Github ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
      - name: Download xmlstarlet
        run: |
          sudo apt-get install xmlstarlet
      - name: Run GitHub Update Script
        run: |
          ./.ci/update-github.sh ${{ github.event.inputs.version }}
