#############################################################################
# GitHub Action to Push Release Notes.
#
#############################################################################
name: "Push Release Notes"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Target Version without (-SNAPSHOT)'
        required: true
jobs:
  releasenotes:
    name: Push releasenotes ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Download xmlstarlet
        run: |
          sudo apt-get install xmlstarlet
      - name: Run Shell Script
        run: |
          ./.ci/update-sources.sh ${{ github.event.inputs.version }}
      - name: Commit and Push
        run: |
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add . && git commit -m "doc: release notes for ${{ github.event.inputs.version }}"
            git push origin master
