////////////////////////////////////////////////////////////////////////////////
// checkstyle: Checks Java source code for adherence to a set of rules.
// Copyright (C) 2001-2021 the original author or authors.
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
////////////////////////////////////////////////////////////////////////////////

package com.puppycrawl.tools.checkstyle.checks.blocks;

import static com.puppycrawl.tools.checkstyle.checks.blocks.EmptyBlockCheck.MSG_KEY_BLOCK_EMPTY;
import static com.puppycrawl.tools.checkstyle.checks.blocks.EmptyBlockCheck.MSG_KEY_BLOCK_NO_STATEMENT;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.fail;

import org.junit.jupiter.api.Test;

import com.puppycrawl.tools.checkstyle.AbstractModuleTestSupport;
import com.puppycrawl.tools.checkstyle.DefaultConfiguration;
import com.puppycrawl.tools.checkstyle.api.CheckstyleException;
import com.puppycrawl.tools.checkstyle.utils.CommonUtil;

public class EmptyBlockCheckTest
    extends AbstractModuleTestSupport {

    @Override
    protected String getPackageLocation() {
        return "com/puppycrawl/tools/checkstyle/checks/blocks/emptyblock";
    }

    /* Additional test for jacoco, since valueOf()
     * is generated by javac and jacoco reports that
     * valueOf() is uncovered.
     */
    @Test
    public void testBlockOptionValueOf() {
        final BlockOption option = BlockOption.valueOf("TEXT");
        assertEquals(BlockOption.TEXT, option, "Invalid valueOf result");
    }

    @Test
    public void testDefault()
            throws Exception {
        final DefaultConfiguration checkConfig =
            createModuleConfig(EmptyBlockCheck.class);
        final String[] expected = {
            "38:13: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT),
            "40:17: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT),
            "42:13: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT),
            "45:17: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT),
            "68:5: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT),
            "76:29: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT),
            "78:41: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT),
            "89:12: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT),
        };
        verify(checkConfig, getPath("InputEmptyBlockSemantic.java"), expected);
    }

    @Test
    public void testText()
            throws Exception {
        final DefaultConfiguration checkConfig =
            createModuleConfig(EmptyBlockCheck.class);
        checkConfig.addAttribute("option", BlockOption.TEXT.toString());
        final String[] expected = {
            "38:13: " + getCheckMessage(MSG_KEY_BLOCK_EMPTY, "try"),
            "40:17: " + getCheckMessage(MSG_KEY_BLOCK_EMPTY, "finally"),
            "68:5: " + getCheckMessage(MSG_KEY_BLOCK_EMPTY, "INSTANCE_INIT"),
            "76:29: " + getCheckMessage(MSG_KEY_BLOCK_EMPTY, "synchronized"),
            "88:12: " + getCheckMessage(MSG_KEY_BLOCK_EMPTY, "STATIC_INIT"),
        };
        verify(checkConfig, getPath("InputEmptyBlockSemanticText.java"), expected);
    }

    @Test
    public void testStatement()
            throws Exception {
        final DefaultConfiguration checkConfig =
            createModuleConfig(EmptyBlockCheck.class);
        checkConfig.addAttribute("option", BlockOption.STATEMENT.toString());
        final String[] expected = {
            "38:13: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT),
            "40:17: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT),
            "42:13: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT),
            "45:17: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT),
            "68:5: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT),
            "76:29: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT),
            "78:41: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT),
            "89:12: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT),
        };
        verify(checkConfig, getPath("InputEmptyBlockSemanticStatement.java"), expected);
    }

    @Test
    public void allowEmptyLoops() throws Exception {
        final DefaultConfiguration checkConfig =
                createModuleConfig(EmptyBlockCheck.class);
        checkConfig.addAttribute("option", BlockOption.STATEMENT.toString());
        checkConfig.addAttribute("tokens", "LITERAL_TRY, LITERAL_CATCH,"
                + "LITERAL_FINALLY, LITERAL_DO, LITERAL_IF,"
                + "LITERAL_ELSE, INSTANCE_INIT, STATIC_INIT, LITERAL_SWITCH");
        final String[] expected = {
            "21:21: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT),
            "24:34: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT),
            "27:21: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT),
            "28:20: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT),
        };
        verify(checkConfig, getPath("InputEmptyBlockSemantic2Statement.java"), expected);
    }

    @Test
    public void allowEmptyLoopsText() throws Exception {
        final DefaultConfiguration checkConfig =
                createModuleConfig(EmptyBlockCheck.class);
        checkConfig.addAttribute("option", BlockOption.TEXT.toString());
        checkConfig.addAttribute("tokens", "LITERAL_TRY, LITERAL_CATCH,"
                + "LITERAL_FINALLY, LITERAL_DO, LITERAL_IF,"
                + "LITERAL_ELSE, INSTANCE_INIT, STATIC_INIT, LITERAL_SWITCH");
        final String[] expected = {
            "26:21: " + getCheckMessage(MSG_KEY_BLOCK_EMPTY, "if"),
            "29:34: " + getCheckMessage(MSG_KEY_BLOCK_EMPTY, "if"),
            "32:21: " + getCheckMessage(MSG_KEY_BLOCK_EMPTY, "if"),
            "33:20: " + getCheckMessage(MSG_KEY_BLOCK_EMPTY, "switch"),
        };
        verify(checkConfig, getPath("InputEmptyBlockSemantic2Text.java"), expected);
    }

    @Test
    public void testInvalidOption() throws Exception {
        final DefaultConfiguration checkConfig = createModuleConfig(EmptyBlockCheck.class);
        checkConfig.addAttribute("option", "invalid_option");

        try {
            final String[] expected = CommonUtil.EMPTY_STRING_ARRAY;

            verify(checkConfig, getPath("InputEmptyBlockSemanticInvalid.java"), expected);
            fail("exception expected");
        }
        catch (CheckstyleException ex) {
            assertEquals("cannot initialize module com.puppycrawl.tools.checkstyle.TreeWalker - "
                        + "cannot initialize module com.puppycrawl.tools.checkstyle.checks."
                        + "blocks.EmptyBlockCheck - "
                        + "Cannot set property 'option' to 'invalid_option'",
                    ex.getMessage(), "Invalid exception message");
        }
    }

    @Test
    public void testAllowEmptyCaseWithText() throws Exception {
        final DefaultConfiguration checkConfig = createModuleConfig(EmptyBlockCheck.class);
        checkConfig.addAttribute("option", BlockOption.TEXT.toString());
        checkConfig.addAttribute("tokens", "LITERAL_CASE");
        final String[] expected = {
            "16:28: " + getCheckMessage(MSG_KEY_BLOCK_EMPTY, "case"),
            "22:13: " + getCheckMessage(MSG_KEY_BLOCK_EMPTY, "case"),
            "33:29: " + getCheckMessage(MSG_KEY_BLOCK_EMPTY, "case"),
            "35:37: " + getCheckMessage(MSG_KEY_BLOCK_EMPTY, "case"),
            "36:29: " + getCheckMessage(MSG_KEY_BLOCK_EMPTY, "case"),
        };
        verify(checkConfig, getPath("InputEmptyBlockCase.java"), expected);
    }

    @Test
    public void testForbidCaseWithoutStmt() throws Exception {
        final DefaultConfiguration checkConfig = createModuleConfig(EmptyBlockCheck.class);
        checkConfig.addAttribute("option", BlockOption.STATEMENT.toString());
        checkConfig.addAttribute("tokens", "LITERAL_CASE");
        final String[] expected = {
            "16:28: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT, "case"),
            "22:13: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT, "case"),
            "26:13: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT, "case"),
            "33:29: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT, "case"),
            "35:37: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT, "case"),
            "36:29: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT, "case"),
            "36:40: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT, "case"),
        };
        verify(checkConfig, getPath("InputEmptyBlockCase2.java"), expected);
    }

    @Test
    public void testAllowEmptyDefaultWithText() throws Exception {
        final DefaultConfiguration checkConfig = createModuleConfig(EmptyBlockCheck.class);
        checkConfig.addAttribute("option", BlockOption.TEXT.toString());
        checkConfig.addAttribute("tokens", "LITERAL_DEFAULT");
        final String[] expected = {
            "15:30: " + getCheckMessage(MSG_KEY_BLOCK_EMPTY, "default"),
            "21:13: " + getCheckMessage(MSG_KEY_BLOCK_EMPTY, "default"),
            "46:22: " + getCheckMessage(MSG_KEY_BLOCK_EMPTY, "default"),
            "54:47: " + getCheckMessage(MSG_KEY_BLOCK_EMPTY, "default"),
            "60:22: " + getCheckMessage(MSG_KEY_BLOCK_EMPTY, "default"),
            "88:13: " + getCheckMessage(MSG_KEY_BLOCK_EMPTY, "default"),
        };
        verify(checkConfig, getPath("InputEmptyBlockDefault.java"), expected);
    }

    @Test
    public void testForbidDefaultWithoutStatement() throws Exception {
        final DefaultConfiguration checkConfig = createModuleConfig(EmptyBlockCheck.class);
        checkConfig.addAttribute("option", BlockOption.STATEMENT.toString());
        checkConfig.addAttribute("tokens", "LITERAL_DEFAULT");
        final String[] expected = {
            "15:30: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT, "default"),
            "21:13: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT, "default"),
            "25:13: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT, "default"),
            "36:30: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT, "default"),
            "46:22: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT, "default"),
            "54:47: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT, "default"),
            "60:22: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT, "default"),
            "75:22: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT, "default"),
            "88:13: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT, "default"),
        };
        verify(checkConfig, getPath("InputEmptyBlockDefault2.java"), expected);
    }

    @Test
    public void testAnnotationDefaultKeyword() throws Exception {
        final DefaultConfiguration checkConfig = createModuleConfig(EmptyBlockCheck.class);
        checkConfig.addAttribute("option", BlockOption.STATEMENT.toString());
        checkConfig.addAttribute("tokens", "LITERAL_DEFAULT");
        final String[] expected = CommonUtil.EMPTY_STRING_ARRAY;
        final String path = getPath("InputEmptyBlockAnnotationDefaultKeyword.java");
        verify(checkConfig, path, expected);
    }

    @Test
    public void testEmptyBlockSwitchExpressions() throws Exception {
        final DefaultConfiguration checkConfig = createModuleConfig(EmptyBlockCheck.class);
        checkConfig.addAttribute("tokens",
            "LITERAL_DEFAULT, LITERAL_CASE, LITERAL_SWITCH");

        final String[] expected = {
            "17:30: " + getCheckMessage(MSG_KEY_BLOCK_NO_STATEMENT, "default"),
            };
        verify(checkConfig,
            getNonCompilablePath("InputEmptyBlockSwitchExpressions.java"), expected);
    }

}
