////////////////////////////////////////////////////////////////////////////////
// checkstyle: Checks Java source code for adherence to a set of rules.
// Copyright (C) 2001-2021 the original author or authors.
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
////////////////////////////////////////////////////////////////////////////////

package com.puppycrawl.tools.checkstyle.checks.blocks;

import static com.puppycrawl.tools.checkstyle.checks.blocks.LeftCurlyCheck.MSG_KEY_LINE_BREAK_AFTER;
import static com.puppycrawl.tools.checkstyle.checks.blocks.LeftCurlyCheck.MSG_KEY_LINE_NEW;
import static com.puppycrawl.tools.checkstyle.checks.blocks.LeftCurlyCheck.MSG_KEY_LINE_PREVIOUS;
import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.fail;

import org.junit.jupiter.api.Test;

import com.puppycrawl.tools.checkstyle.AbstractModuleTestSupport;
import com.puppycrawl.tools.checkstyle.DefaultConfiguration;
import com.puppycrawl.tools.checkstyle.api.CheckstyleException;
import com.puppycrawl.tools.checkstyle.api.TokenTypes;
import com.puppycrawl.tools.checkstyle.utils.CommonUtil;

public class LeftCurlyCheckTest extends AbstractModuleTestSupport {

    @Override
    protected String getPackageLocation() {
        return "com/puppycrawl/tools/checkstyle/checks/blocks/leftcurly";
    }

    /* Additional test for jacoco, since valueOf()
     * is generated by javac and jacoco reports that
     * valueOf() is uncovered.
     */
    @Test
    public void testLeftCurlyOptionValueOf() {
        final LeftCurlyOption option = LeftCurlyOption.valueOf("NL");
        assertEquals(LeftCurlyOption.NL, option, "Invalid valueOf result");
    }

    @Test
    public void testGetRequiredTokens() {
        final LeftCurlyCheck checkObj = new LeftCurlyCheck();
        assertArrayEquals(CommonUtil.EMPTY_INT_ARRAY, checkObj.getRequiredTokens(),
                "LeftCurlyCheck#getRequiredTokens should return empty array by default");
    }

    @Test
    public void testDefault() throws Exception {
        final DefaultConfiguration checkConfig = createModuleConfig(LeftCurlyCheck.class);
        final String[] expected = {
            "7:1: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 1),
            "9:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "13:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "17:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "21:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
        };
        verify(checkConfig, getPath("InputLeftCurlyTestDefault.java"), expected);
    }

    @Test
    public void testNl() throws Exception {
        final DefaultConfiguration checkConfig = createModuleConfig(LeftCurlyCheck.class);
        checkConfig.addAttribute("option", LeftCurlyOption.NL.toString());
        final String[] expected = {
            "27:14: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 14),
            "31:14: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 14),
            "36:18: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 18),
            "40:18: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 18),
            "45:12: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 12),
            "50:18: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 18),
            "55:20: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 20),
            "58:27: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 27),
            "59:23: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 23),
            "60:25: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 25),
        };
        verify(checkConfig, getPath("InputLeftCurlyDefaultTestNl.java"), expected);
    }

    @Test
    public void testNlow() throws Exception {
        final DefaultConfiguration checkConfig = createModuleConfig(LeftCurlyCheck.class);
        checkConfig.addAttribute("option", LeftCurlyOption.NLOW.toString());
        final String[] expected = {
            "8:1: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 1),
            "10:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "14:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "18:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "22:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "27:14: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 14),
            "31:14: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 14),
            "36:18: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 18),
            "40:18: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 18),
            "45:12: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 12),
            "50:18: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 18),
            "55:20: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 20),
        };
        verify(checkConfig, getPath("InputLeftCurlyDefaultTestNlow.java"), expected);
    }

    @Test
    public void testDefault2() throws Exception {
        final DefaultConfiguration checkConfig = createModuleConfig(LeftCurlyCheck.class);
        final String[] expected = {
            "7:1: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 1),
            "12:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "19:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "22:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "26:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "34:1: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 1),
            "36:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "41:9: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 9),
            "44:9: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 9),
            "48:9: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 9),
            "60:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "64:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "72:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "75:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "79:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
        };
        verify(checkConfig, getPath("InputLeftCurlyMethod.java"), expected);
    }

    @Test
    public void testNewline2() throws Exception {
        final DefaultConfiguration checkConfig = createModuleConfig(LeftCurlyCheck.class);
        checkConfig.addAttribute("option", LeftCurlyOption.NL.toString());
        final String[] expected = {
            "10:44: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 44),
            "17:20: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 20),
            "30:31: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 31),
            "39:24: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 24),
            "52:35: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 35),
            "56:17: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 17),
            "70:20: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 20),
            "83:31: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 31),
        };
        verify(checkConfig, getPath("InputLeftCurlyMethodTestNewLine2.java"), expected);
    }

    @Test
    public void testDefault3() throws Exception {
        final DefaultConfiguration checkConfig = createModuleConfig(LeftCurlyCheck.class);
        final String[] expected = {
            "7:1: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 1),
            "10:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "14:9: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 9),
            "16:13: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 13),
            "18:17: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 17),
            "25:17: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 17),
            "29:17: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 17),
            "37:13: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 13),
            "41:13: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 13),
            "47:9: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 9),
            "49:13: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 13),
            "58:9: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 9),
            "71:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "78:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "84:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "92:19: " + getCheckMessage(MSG_KEY_LINE_BREAK_AFTER, "{", 19),
            "101:1: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 1),
            "104:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "113:1: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 1),
            "115:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "124:1: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 1),
            "126:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "128:9: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 9),
            "143:1: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 1),
            "152:1: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 1),
            "159:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
        };
        verify(checkConfig, getPath("InputLeftCurlyTestDefault3.java"), expected);
    }

    @Test
    public void testNewline3() throws Exception {
        final DefaultConfiguration checkConfig = createModuleConfig(LeftCurlyCheck.class);
        checkConfig.addAttribute("option", LeftCurlyOption.NL.toString());
        final String[] expected = {
            "22:33: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 33),
            "87:19: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 19),
            "93:19: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 19),
            "138:49: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 49),
            "154:12: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 12),
            "161:16: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 16),
        };
        verify(checkConfig, getPath("InputLeftCurlyTestNewLine3.java"), expected);
    }

    @Test
    public void testMissingBraces() throws Exception {
        final DefaultConfiguration checkConfig = createModuleConfig(LeftCurlyCheck.class);
        final String[] expected = {
            "7:1: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 1),
            "10:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "16:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "29:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "46:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "64:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "100:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
        };
        verify(checkConfig, getPath("InputLeftCurlyTestMissingBraces.java"), expected);
    }

    @Test
    public void testDefaultWithAnnotations() throws Exception {
        final DefaultConfiguration checkConfig = createModuleConfig(LeftCurlyCheck.class);
        final String[] expected = {
            "13:1: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 1),
            "17:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "24:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "30:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "53:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "61:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
        };
        verify(checkConfig, getPath("InputLeftCurlyTestDefaultWithAnnotations.java"), expected);
    }

    @Test
    public void testNlWithAnnotations() throws Exception {
        final DefaultConfiguration checkConfig = createModuleConfig(LeftCurlyCheck.class);
        checkConfig.addAttribute("option", LeftCurlyOption.NL.toString());
        final String[] expected = {
            "39:55: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 55),
            "42:41: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 41),
            "48:27: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 27),
            "70:42: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 42),
        };
        verify(checkConfig, getPath("InputLeftCurlyTestNlWithAnnotations.java"), expected);
    }

    @Test
    public void testNlowWithAnnotations() throws Exception {
        final DefaultConfiguration checkConfig = createModuleConfig(LeftCurlyCheck.class);
        checkConfig.addAttribute("option", LeftCurlyOption.NLOW.toString());
        final String[] expected = {
            "14:1: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 1),
            "18:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "25:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "31:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "54:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "62:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
        };
        verify(checkConfig, getPath("InputLeftCurlyTestNlowWithAnnotations.java"), expected);
    }

    @Test
    public void testLineBreakAfter() throws Exception {
        final DefaultConfiguration checkConfig = createModuleConfig(LeftCurlyCheck.class);
        checkConfig.addAttribute("option", LeftCurlyOption.EOL.toString());
        final String[] expected = {
            "13:1: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 1),
            "16:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "20:9: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 9),
            "22:13: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 13),
            "24:17: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 17),
            "30:22: " + getCheckMessage(MSG_KEY_LINE_BREAK_AFTER, "{", 22),
            "32:17: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 17),
            "39:33: " + getCheckMessage(MSG_KEY_LINE_BREAK_AFTER, "{", 33),
            "40:21: " + getCheckMessage(MSG_KEY_LINE_BREAK_AFTER, "{", 21),
            "43:29: " + getCheckMessage(MSG_KEY_LINE_BREAK_AFTER, "{", 29),
            "43:34: " + getCheckMessage(MSG_KEY_LINE_BREAK_AFTER, "{", 34),
            "49:37: " + getCheckMessage(MSG_KEY_LINE_BREAK_AFTER, "{", 37),
            "55:12: " + getCheckMessage(MSG_KEY_LINE_BREAK_AFTER, "{", 12),
            "58:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "60:19: " + getCheckMessage(MSG_KEY_LINE_BREAK_AFTER, "{", 19),
            "70:1: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 1),
        };
        verify(checkConfig, getPath("InputLeftCurlyTestLineBreakAfter.java"), expected);
    }

    @Test
    public void testIgnoreEnumsOptionTrue() throws Exception {
        final DefaultConfiguration checkConfig = createModuleConfig(LeftCurlyCheck.class);
        checkConfig.addAttribute("option", LeftCurlyOption.EOL.toString());
        checkConfig.addAttribute("ignoreEnums", "true");
        final String[] expectedWhileTrue = {
            "13:44: " + getCheckMessage(MSG_KEY_LINE_BREAK_AFTER, "{", 44),
        };
        verify(checkConfig, getPath("InputLeftCurlyIgnoreEnumsOptTrue.java"), expectedWhileTrue);
    }

    @Test
    public void testIgnoreEnumsOptionFalse() throws Exception {
        final DefaultConfiguration checkConfig = createModuleConfig(LeftCurlyCheck.class);
        checkConfig.addAttribute("option", LeftCurlyOption.EOL.toString());
        checkConfig.addAttribute("ignoreEnums", "false");
        final String[] expectedWhileFalse = {
            "9:17: " + getCheckMessage(MSG_KEY_LINE_BREAK_AFTER, "{", 17),
            "13:44: " + getCheckMessage(MSG_KEY_LINE_BREAK_AFTER, "{", 44),
        };
        verify(checkConfig, getPath("InputLeftCurlyIgnoreEnumsOptFalse.java"), expectedWhileFalse);
    }

    @Test
    public void testDefaultLambda() throws Exception {
        final DefaultConfiguration checkConfig = createModuleConfig(LeftCurlyCheck.class);
        final String[] expected = {
            "7:1: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 1),
            "14:32: " + getCheckMessage(MSG_KEY_LINE_BREAK_AFTER, "{", 32),
            "17:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
        };
        verify(checkConfig, getPath("InputLeftCurlyTestDefaultLambda.java"),
                expected);
    }

    @Test
    public void testNewLineOptionWithLambda() throws Exception {
        final DefaultConfiguration checkConfig = createModuleConfig(LeftCurlyCheck.class);
        checkConfig.addAttribute("option", LeftCurlyOption.NL.toString());
        final String[] expected = {
            "9:32: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 32),
            "15:32: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 32),
        };
        verify(checkConfig, getPath("InputLeftCurlyTestNewLineOptionWithLambda.java"),
                expected);
    }

    @Test
    public void testEolSwitch() throws Exception {
        final DefaultConfiguration checkConfig = createModuleConfig(LeftCurlyCheck.class);
        checkConfig.addAttribute("option", LeftCurlyOption.EOL.toString());
        final String[] expected = {
            "13:13: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 13),
            "17:13: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 13),
            "24:13: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 13),
            "38:13: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 13),
            "43:13: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 13),
        };
        verify(checkConfig, getPath("InputLeftCurlyTestEolSwitch.java"), expected);
    }

    @Test
    public void testNlSwitch() throws Exception {
        final DefaultConfiguration checkConfig = createModuleConfig(LeftCurlyCheck.class);
        checkConfig.addAttribute("option", LeftCurlyOption.NL.toString());
        final String[] expected = {
            "15:21: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 21),
            "47:14: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 14),
        };
        verify(checkConfig, getPath("InputLeftCurlyTestNlSwitch.java"), expected);
    }

    @Test
    public void testNlowSwitch() throws Exception {
        final DefaultConfiguration checkConfig = createModuleConfig(LeftCurlyCheck.class);
        checkConfig.addAttribute("option", LeftCurlyOption.NLOW.toString());
        final String[] expected = {
            "13:13: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 13),
        };
        verify(checkConfig, getPath("InputLeftCurlyTestNlowSwitch.java"), expected);
    }

    @Test
    public void testLeftCurlySwitchExpressions() throws Exception {
        final DefaultConfiguration checkConfig = createModuleConfig(LeftCurlyCheck.class);
        final String[] expected = {
            "12:9: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 9),
            "14:17: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 17),
            "19:17: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 17),
            "24:17: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 17),
            "28:17: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 17),
            "37:17: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 17),
            "39:21: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 21),
            "43:21: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 21),
            "47:21: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 21),
            "51:21: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 21),

            };
        verify(checkConfig,
            getNonCompilablePath("InputLeftCurlyTestSwitchExpressions.java"), expected);
    }

    @Test
    public void testLeftCurlySwitchExpressionsNewLine() throws Exception {
        final DefaultConfiguration checkConfig = createModuleConfig(LeftCurlyCheck.class);
        checkConfig.addAttribute("option", LeftCurlyOption.NL.toString());

        final String[] expected = {
            "9:57: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 57),
            "10:25: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 25),
            "35:25: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 25),
            "46:23: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 23),

            };
        verify(checkConfig,
            getNonCompilablePath("InputLeftCurlyTestSwitchExpressionsNewLine.java"),
            expected);
    }

    @Test
    public void testGetAcceptableTokens() {
        final LeftCurlyCheck check = new LeftCurlyCheck();
        final int[] actual = check.getAcceptableTokens();
        final int[] expected = {
            TokenTypes.ANNOTATION_DEF,
            TokenTypes.CLASS_DEF,
            TokenTypes.CTOR_DEF,
            TokenTypes.ENUM_CONSTANT_DEF,
            TokenTypes.ENUM_DEF,
            TokenTypes.INTERFACE_DEF,
            TokenTypes.LAMBDA,
            TokenTypes.LITERAL_CASE,
            TokenTypes.LITERAL_CATCH,
            TokenTypes.LITERAL_DEFAULT,
            TokenTypes.LITERAL_DO,
            TokenTypes.LITERAL_ELSE,
            TokenTypes.LITERAL_FINALLY,
            TokenTypes.LITERAL_FOR,
            TokenTypes.LITERAL_IF,
            TokenTypes.LITERAL_SWITCH,
            TokenTypes.LITERAL_SYNCHRONIZED,
            TokenTypes.LITERAL_TRY,
            TokenTypes.LITERAL_WHILE,
            TokenTypes.METHOD_DEF,
            TokenTypes.OBJBLOCK,
            TokenTypes.STATIC_INIT,
            TokenTypes.RECORD_DEF,
            TokenTypes.COMPACT_CTOR_DEF,
        };
        assertArrayEquals(expected, actual, "Default acceptable tokens are invalid");
    }

    @Test
    public void testFirstLine() throws Exception {
        final DefaultConfiguration checkConfig = createModuleConfig(LeftCurlyCheck.class);
        checkConfig.addAttribute("option", LeftCurlyOption.EOL.toString());
        final String[] expected = CommonUtil.EMPTY_STRING_ARRAY;
        verify(checkConfig, getPath("InputLeftCurlyTestFirstLine.java"), expected);
    }

    @Test
    public void testCoverageIncrease() throws Exception {
        final DefaultConfiguration checkConfig = createModuleConfig(LeftCurlyCheck.class);
        checkConfig.addAttribute("option", LeftCurlyOption.NLOW.toString());
        final String[] expected = {
            "12:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "21:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "30:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "39:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "53:14: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 14),
            "58:18: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 18),
            "62:18: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 18),
            "67:12: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 12),
            "72:18: " + getCheckMessage(MSG_KEY_LINE_NEW, "{", 18),
        };
        verify(checkConfig, getPath("InputLeftCurlyTestCoverageIncrease.java"), expected);
    }

    @Test
    public void testLeftCurlyRecordsAndCompactCtors() throws Exception {
        final DefaultConfiguration checkConfig = createModuleConfig(LeftCurlyCheck.class);
        checkConfig.addAttribute("option", LeftCurlyOption.NLOW.toString());
        final String[] expected = {
            "12:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "14:9: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 9),
            "24:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "26:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            "33:9: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 9),
            "46:5: " + getCheckMessage(MSG_KEY_LINE_PREVIOUS, "{", 5),
            };
        verify(checkConfig,
            getNonCompilablePath("InputLeftCurlyTestRecordsAndCompactCtors.java"), expected);
    }

    @Test
    public void testInvalidOption() throws Exception {
        final DefaultConfiguration checkConfig = createModuleConfig(LeftCurlyCheck.class);
        checkConfig.addAttribute("option", "invalid_option");

        try {
            final String[] expected = CommonUtil.EMPTY_STRING_ARRAY;

            verify(checkConfig, getPath("InputLeftCurlyTestInvalidOption.java"), expected);
            fail("exception expected");
        }
        catch (CheckstyleException ex) {
            assertEquals("cannot initialize module com.puppycrawl.tools.checkstyle.TreeWalker - "
                    + "cannot initialize module com.puppycrawl.tools.checkstyle.checks."
                    + "blocks.LeftCurlyCheck - "
                    + "Cannot set property 'option' to 'invalid_option'",
                ex.getMessage(), "Invalid exception message");
        }
    }

}
