///////////////////////////////////////////////////////////////////////////////////////////////
// checkstyle: Checks Java source code and other text files for adherence to a set of rules.
// Copyright (C) 2001-2026 the original author or authors.
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
///////////////////////////////////////////////////////////////////////////////////////////////

package com.puppycrawl.tools.checkstyle.checks.blocks;

import static com.google.common.truth.Truth.assertWithMessage;
import static com.puppycrawl.tools.checkstyle.checks.blocks.RightCurlyCheck.MSG_KEY_LINE_ALONE;
import static com.puppycrawl.tools.checkstyle.checks.blocks.RightCurlyCheck.MSG_KEY_LINE_BREAK_BEFORE;
import static com.puppycrawl.tools.checkstyle.checks.blocks.RightCurlyCheck.MSG_KEY_LINE_SAME;
import static com.puppycrawl.tools.checkstyle.internal.utils.TestUtil.getExpectedThrowable;

import org.junit.jupiter.api.Test;

import com.puppycrawl.tools.checkstyle.AbstractModuleTestSupport;
import com.puppycrawl.tools.checkstyle.api.CheckstyleException;
import com.puppycrawl.tools.checkstyle.utils.CommonUtil;

public class RightCurlyCheckTest extends AbstractModuleTestSupport {

    @Override
    public String getPackageLocation() {
        return "com/puppycrawl/tools/checkstyle/checks/blocks/rightcurly";
    }

    /* Additional test for jacoco, since valueOf()
     * is generated by javac and jacoco reports that
     * valueOf() is uncovered.
     */
    @Test
    public void testRightCurlyOptionValueOf() {
        final RightCurlyOption option = RightCurlyOption.valueOf("ALONE");
        assertWithMessage("Invalid valueOf result")
            .that(option)
            .isEqualTo(RightCurlyOption.ALONE);
    }

    @Test
    public void testDefault() throws Exception {
        final String[] expected = {
            "26:17: " + getCheckMessage(MSG_KEY_LINE_SAME, "}", 17),
            "29:17: " + getCheckMessage(MSG_KEY_LINE_SAME, "}", 17),
            "41:13: " + getCheckMessage(MSG_KEY_LINE_SAME, "}", 13),
            "45:13: " + getCheckMessage(MSG_KEY_LINE_SAME, "}", 13),
            "94:27: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 27),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyLeftTestDefault.java"), expected);
    }

    @Test
    public void testSame() throws Exception {
        final String[] expected = {
            "27:17: " + getCheckMessage(MSG_KEY_LINE_SAME, "}", 17),
            "30:17: " + getCheckMessage(MSG_KEY_LINE_SAME, "}", 17),
            "42:13: " + getCheckMessage(MSG_KEY_LINE_SAME, "}", 13),
            "46:13: " + getCheckMessage(MSG_KEY_LINE_SAME, "}", 13),
            "88:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "95:27: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 27),
            "190:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "191:41: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 41),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyLeftTestSame.java"), expected);
    }

    @Test
    public void testSameOmitOneLiners() throws Exception {
        final String[] expected = CommonUtil.EMPTY_STRING_ARRAY;
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestSameOmitOneLiners.java"), expected);
    }

    @Test
    public void testSameDoesNotComplainForNonMultilineConstructs() throws Exception {
        final String[] expected = CommonUtil.EMPTY_STRING_ARRAY;
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestSame.java"), expected);
    }

    @Test
    public void testAlone() throws Exception {
        final String[] expected = {
            "58:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "95:27: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 27),
            "99:41: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 41),
            "175:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "177:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "179:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "180:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "185:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "190:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "191:53: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 53),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyLeftTestAlone.java"), expected);
    }

    @Test
    public void testNewLine() throws Exception {
        final String[] expected = {
            "87:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "112:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "112:6: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 6),
            "123:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "123:6: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 6),
            "137:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "137:6: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 6),
            "145:37: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 37),
            "150:41: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 41),
            "153:31: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 31),
            "155:39: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 39),
            "198:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "203:30: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 30),
            "206:39: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 39),
            "212:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "212:10: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 10),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyLeftTestNewLine.java"), expected);
    }

    @Test
    public void testShouldStartLine2() throws Exception {
        final String[] expected = {
            "87:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "112:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "112:6: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 6),
            "123:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "123:6: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 6),
            "137:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "137:6: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 6),
            "198:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "203:30: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 30),
            "212:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "212:10: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 10),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyLeftTestShouldStartLine2.java"), expected);
    }

    @Test
    public void testForceLineBreakBefore() throws Exception {
        final String[] expected = {
            "39:43: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 43),
            "42:17: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 17),
            "45:71: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 71),
            "47:38: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 38),
            "51:25: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 25),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestForceLineBreakBefore.java"), expected);
    }

    @Test
    public void testForceLineBreakBefore2() throws Exception {
        final String[] expected = CommonUtil.EMPTY_STRING_ARRAY;
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestForceLineBreakBefore2.java"), expected);
    }

    @Test
    public void testNullPointerException() throws Exception {
        final String[] expected = CommonUtil.EMPTY_STRING_ARRAY;
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestNullPointerException.java"), expected);
    }

    @Test
    public void testWithAnnotations() throws Exception {
        final String[] expected = {
            "19:77: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 77),
            "22:65: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 65),
            "33:46: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 46),
            "37:31: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 31),
            "40:35: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 35),
            "43:36: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 36),
            "49:73: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 73),
            "51:37: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 37),
            "56:66: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 66),
            "59:96: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 96),
            "62:30: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 30),
            "65:30: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 30),
            "68:29: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 29),
            "72:38: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 38),
            "73:31: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 31),
            "79:62: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 62),
            "88:28: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 28),
            "90:21: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 21),
            "92:20: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 20),
            "94:14: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 14),
            "105:26: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 26),
            "106:20: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 20),
            "115:29: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 29),
            "115:38: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 38),
            "119:29: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 29),
            "119:38: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 38),
            "123:40: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 40),
            "123:88: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 88),
            "126:18: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 18),
            "130:23: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 23),
            "133:37: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 37),
            "135:30: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 30),
            "139:77: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 77),
            "148:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "150:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "150:33: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 33),
            "162:75: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 75),
            "163:58: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 58),
            "163:74: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 74),
            "164:58: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 58),
            "166:58: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 58),
            "166:73: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 73),
            "172:37: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 37),
            "179:37: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 37),
            "194:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "201:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "201:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "209:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "209:10: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 10),
            "213:54: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 54),
            "213:55: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 55),
            "216:75: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 75),
            "216:76: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 76),
            "216:77: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 77),
            "220:76: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 76),
            "228:27: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 27),
            "232:31: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 31),
            "235:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "237:29: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 29),
            "240:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "243:30: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 30),
            "246:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "249:39: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 39),
            "251:56: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 56),
            "254:24: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 24),
            "264:29: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 29),
            "266:40: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 40),
            "270:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "273:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "275:61: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 61),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestWithAnnotations.java"), expected);
    }

    @Test
    public void testAloneOrSingleLine() throws Exception {
        final String[] expected = {
            "71:26: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 26),
            "85:42: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 42),
            "88:18: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 18),
            "96:30: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 30),
            "100:77: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 77),
            "108:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "110:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "121:75: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 75),
            "123:77: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 77),
            "123:93: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 93),
            "125:77: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 77),
            "127:64: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 64),
            "127:80: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 80),
            "133:37: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 37),
            "140:37: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 37),
            "155:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "162:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "162:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "171:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "171:10: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 10),
            "175:54: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 54),
            "175:55: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 55),
            "178:75: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 75),
            "178:76: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 76),
            "178:77: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 77),
            "190:27: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 27),
            "196:24: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 24),
            "199:24: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 24),
            "202:24: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 24),
            "208:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "210:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "212:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "213:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "218:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "223:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "224:39: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 39),
            "232:24: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 24),
            "244:30: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 30),
            "250:29: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 29),
            "250:38: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 38),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestAloneOrSingleline.java"), expected);
    }

    @Test
    public void testAloneOrSingleLineTryCatchBlock() throws Exception {
        final String[] expected = CommonUtil.EMPTY_STRING_ARRAY;
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestAloneOrSinglelineTryCatchBlock.java"), expected);
    }

    @Test
    public void testCatchWithoutFinally() throws Exception {
        final String[] expected = {
            "20:9: " + getCheckMessage(MSG_KEY_LINE_SAME, "}", 9),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestWithoutFinally.java"), expected);
    }

    @Test
    public void testSingleLineClass() throws Exception {
        final String[] expected = {
            "30:56: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 56),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestSingleLineClass.java"), expected);
    }

    @Test
    public void testInvalidOption() {

        final CheckstyleException exc = getExpectedThrowable(CheckstyleException.class,
                () -> {
                    final String[] expected = CommonUtil.EMPTY_STRING_ARRAY;
                    verifyWithInlineConfigParser(
                            getPath("InputRightCurlyTestInvalidOption.java"), expected);
                });
        assertWithMessage("Invalid exception message")
            .that(exc.getMessage())
            .isEqualTo("cannot initialize module com.puppycrawl.tools.checkstyle.TreeWalker - "
                + "cannot initialize module com.puppycrawl.tools.checkstyle.checks."
                + "blocks.RightCurlyCheck");
    }

    @Test
    public void testRightCurlySameAndLiteralDo() throws Exception {
        final String[] expected = {
            "71:9: " + getCheckMessage(MSG_KEY_LINE_SAME, "}", 9),
            "76:13: " + getCheckMessage(MSG_KEY_LINE_SAME, "}", 13),
            "92:9: " + getCheckMessage(MSG_KEY_LINE_SAME, "}", 9),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestSameAndLiteralDo.java"), expected);
    }

    @Test
    public void testTryWithResourceSame() throws Exception {
        final String[] expected = {
            "20:9: " + getCheckMessage(MSG_KEY_LINE_SAME, "}", 9),
            "34:67: " + getCheckMessage(MSG_KEY_LINE_SAME, "}", 67),
            "47:15: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 15),
            "49:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestTryWithResourceSame.java"), expected);
    }

    @Test
    public void testTryWithResourceAlone() throws Exception {
        final String[] expected = {
            "28:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "34:67: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 67),
            "35:35: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 35),
            "38:64: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 64),
            "38:92: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 92),
            "45:67: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 67),
            "47:15: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 15),
            "49:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestTryWithResourceAlone.java"), expected);
    }

    @Test
    public void testTryWithResourceAloneSingle() throws Exception {
        final String[] expected = {
            "28:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "44:15: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 15),
            "46:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTryWithResourceAloneSingle.java"), expected);
    }

    @Test
    public void testBracePolicyAloneAndSinglelineIfBlocks() throws Exception {
        final String[] expected = {
            "14:32: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 32),
            "16:45: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 45),
            "16:47: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 47),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestSinglelineIfBlocks.java"), expected);
    }

    @Test
    public void testRightCurlyIsAloneLambda() throws Exception {
        final String[] expected = CommonUtil.EMPTY_STRING_ARRAY;
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestIsAloneLambda.java"), expected);
    }

    @Test
    public void testRightCurlyIsAloneOrSinglelineLambda() throws Exception {
        final String[] expected = CommonUtil.EMPTY_STRING_ARRAY;
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestIsAloneOrSinglelineLambda.java"), expected);
    }

    @Test
    public void testRightCurlyIsSameLambda() throws Exception {
        final String[] expected = CommonUtil.EMPTY_STRING_ARRAY;
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestIsSameLambda.java"), expected);
    }

    @Test
    public void testOptionAlone() throws Exception {
        final String[] expected = {
            "17:15: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 15),
            "18:21: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 21),
            "22:26: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 26),
            "31:37: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 37),
            "48:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "52:37: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 37),
            "55:30: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 30),
            "57:27: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 27),
            "59:17: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 17),
            "61:53: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 53),
            "63:27: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 27),
            "63:52: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 52),
            "76:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "76:11: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 11),
            "80:39: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 39),
            "82:56: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 56),
            "85:24: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 24),
            "97:30: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 30),
            "100:39: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 39),
            "106:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "106:10: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 10),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestOptionAlone.java"),
                expected);
    }

    @Test
    public void testOptionAloneOrSingleLine() throws Exception {
        final String[] expected = {
            "22:26: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 26),
            "31:37: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 37),
            "39:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "48:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "52:37: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 37),
            "73:24: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 24),
            "78:30: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 30),
            "87:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "87:10: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 10),
        };
        verifyWithInlineConfigParser(
                getPath(
                "InputRightCurlyTestOptionAloneOrSingleLine.java"), expected);
    }

    @Test
    public void testBlocksEndingWithSemiOptionSame() throws Exception {
        final String[] expected = {
            "17:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "22:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "28:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "36:29: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 29),
            "42:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "45:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "52:20: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 20),
            "58:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "61:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "66:30: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 30),
            "75:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "75:11: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 11),
            "79:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestOptSameBlocksWithSemi.java"), expected);
    }

    @Test
    public void testBlocksEndingWithSemiOptionAlone() throws Exception {
        final String[] expected = {
            "14:31: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 31),
            "17:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "19:29: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 29),
            "22:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "25:30: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 30),
            "28:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "36:29: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 29),
            "38:40: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 40),
            "42:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "45:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "47:61: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 61),
            "49:19: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 19),
            "52:20: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 20),
            "54:34: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 34),
            "58:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "61:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "66:30: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 30),
            "72:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "72:11: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 11),
            "76:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestOptAloneBlocksWithSemi.java"), expected);
    }

    @Test
    public void testBlocksEndingWithSemiOptionAloneOrSingleLine() throws Exception {
        final String[] expected = {
            "17:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "22:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "28:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "36:29: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 29),
            "42:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "45:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "52:20: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 20),
            "58:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "61:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "66:30: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 30),
            "75:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "75:11: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 11),
            "79:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestOptAloneOrSingleLineBlocksWithSemi.java"), expected);
    }

    @Test
    public void testNewTokensAlone() throws Exception {
        final String[] expected = {
            "14:19: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 19),
            "17:20: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 20),
            "19:34: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 34),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestNewTokensAlone.java"), expected);
    }

    @Test
    public void testNewTokensAloneOrSingleLine() throws Exception {
        final String[] expected = {
            "17:20: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 20),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyNewTokensAloneOrSingleLine.java"), expected);
    }

    @Test
    public void testNewTokensSame() throws Exception {
        final String[] expected = {
            "17:20: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 20),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestSameNewTokens.java"), expected);
    }

    @Test
    public void testRightCurlyDoubleBrace() throws Exception {
        final String[] expected = {
            "15:1: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 1),
            "15:2: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 2),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestDoubleBrace.java"), expected);
    }

    @Test
    public void testRightCurlyEmptyOnSingleLine() throws Exception {
        final String[] expected = CommonUtil.EMPTY_STRING_ARRAY;
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestEmptyOnSingleLine.java"), expected);
    }

    @Test
    public void testRightCurlyEndOfFile() throws Exception {
        final String[] expected = {
            "17:2: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 2),
            "17:3: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 3),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestEndOfFile.java"), expected);
    }

    @Test
    public void testRightCurlyRecordsAndCompactCtors() throws Exception {
        final String[] expected = {
            "24:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "24:11: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 11),
            "28:21: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 21),
            "33:23: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 23),
            "35:37: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 37),
            "42:68: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 68),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestRecordsAndCompactCtors.java"), expected);
    }

    @Test
    public void testRightCurlyWithEmoji() throws Exception {
        final String[] expected = {
            "25:13: " + getCheckMessage(MSG_KEY_LINE_SAME, "}", 13),
            "29:13: " + getCheckMessage(MSG_KEY_LINE_SAME, "}", 13),
            "50:9: " + getCheckMessage(MSG_KEY_LINE_SAME, "}", 9),
            "70:50: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 50),
            "79:44: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 44),
            "85:41: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 41),

        };
        verifyWithInlineConfigParser(getPath("InputRightCurlyWithEmoji.java"), expected);
    }

    @Test
    public void testRightCurlyWithEmojiAloneOrSingleLine() throws Exception {
        final String[] expected = {
            "25:38: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 38),
            "31:43: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 43),
            "41:45: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 45),
            "52:41: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 41),
            "55:31: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 31),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyWithEmojiAloneOrSingleLine.java"), expected);
    }

    @Test
    public void testUppercaseOptionProperty() throws Exception {
        final String[] expected = {
            "17:46: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 46),
            "22:35: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 35),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyWithUppercaseOptionProperty.java"), expected);
    }

    @Test
    public void testRightCurlyWithIfElseAlone() throws Exception {
        final String[] expected = {
            "20:12: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 12),
            "28:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestIfElseAlone.java"), expected);
    }

    @Test
    public void testSwitchCase() throws Exception {
        final String[] expected = {
            "21:24: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 24),
            "28:27: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 27),
            "52:46: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 46),
            "70:68: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 68),
            "76:74: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 74),
            "112:17: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 17),
            "116:21: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 21),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestSwitchCase.java"), expected);
    }

    @Test
    public void testSwitchCase2() throws Exception {
        final String[] expected = {
            "21:24: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 24),
            "28:27: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 27),
            "115:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestSwitchCase2.java"), expected);
    }

    @Test
    public void testSwitchCase3() throws Exception {
        final String[] expected = {
            "16:22: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 22),
            "18:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "20:36: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 36),
            "26:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "27:37: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 37),
            "29:22: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 22),
            "30:22: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 22),
            "38:26: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 26),
            "38:27: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 27),
            "44:40: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 40),
            "44:41: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 41),
            "49:46: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 46),
            "51:32: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 32),
            "51:33: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 33),
            "53:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "53:14: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 14),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestSwitchCase3.java"), expected);
    }

    @Test
    public void testSwitchCase4() throws Exception {
        final String[] expected = {
            "18:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "20:36: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 36),
            "26:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "27:37: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 37),
            "29:22: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 22),
            "36:41: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 41),
            "36:42: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 42),
            "41:46: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 46),
            "43:32: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 32),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestSwitchCase4.java"), expected);
    }

    @Test
    public void testSwitchCase5() throws Exception {
        final String[] expected = {
            "18:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "20:36: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 36),
            "26:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "27:37: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 37),
            "29:22: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 22),
            "36:41: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 41),
            "36:42: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 42),
            "41:46: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 46),
            "43:32: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 32),
            "66:49: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 49),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestSwitchCase5.java"), expected);
    }

    @Test
    public void testSwitchExpression() throws Exception {
        final String[] expected = {
            "49:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "57:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "93:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestSwitchExpression.java"), expected);
    }

    @Test
    public void testSwitchExpression2() throws Exception {
        final String[] expected = {
            "47:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "55:5: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 5),
            "78:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
            "91:9: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 9),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestSwitchExpression2.java"), expected);
    }

    @Test
    public void testSwitchExpression3() throws Exception {
        final String[] expected = CommonUtil.EMPTY_STRING_ARRAY;
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestSwitchExpression3.java"), expected);
    }

    @Test
    public void testSwitchExpression4() throws Exception {
        final String[] expected = {
            "117:28: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 28),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestSwitchExpression4.java"), expected);
    }

    @Test
    public void testSwitchExpression5() throws Exception {
        final String[] expected = CommonUtil.EMPTY_STRING_ARRAY;
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestSwitchExpression5.java"), expected);
    }

    @Test
    public void testSwitchWithComment() throws Exception {
        final String[] expected = {
            "17:66: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 66),
            "24:61: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 61),
            "25:57: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 57),
            "32:23: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 23),
            "33:19: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 19),
            "38:23: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 23),
            "39:33: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 33),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestWithComment.java"), expected);
    }

    @Test
    public void testSwitchExpression6() throws Exception {
        final String[] expected = CommonUtil.EMPTY_STRING_ARRAY;
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestSwitchExpression6.java"), expected);
    }

    @Test
    public void testSwitchExpression7() throws Exception {
        final String[] expected = CommonUtil.EMPTY_STRING_ARRAY;
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestSwitchExpression7.java"), expected);
    }

    @Test
    public void testCaseBlocksInSwitchStatementAlone() throws Exception {
        final String[] expected = {
            "34:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "45:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "74:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "79:44: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 44),
            "91:39: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 39),
            "98:42: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 42),
            "108:35: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 35),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyCaseBlocksInSwitchStatementAlone.java"), expected);
    }

    @Test
    public void testCaseBlocksInSwitchStatementAlone2() throws Exception {
        final String[] expected = {
            "18:15: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 15),
            "27:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "39:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "42:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "50:24: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 24),
            "50:45: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 45),
            "58:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "69:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "69:26: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 26),
            "76:34: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 34),
            "76:47: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 47),
            "83:23: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 23),
            "103:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyCaseBlocksInSwitchStatementAlone2.java"), expected);
    }

    @Test
    public void testCaseBlocksInSwitchStatementAloneOrSingleLine() throws Exception {
        final String[] expected = {
            "34:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "45:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "74:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "79:51: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 51),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyCaseBlocksInSwitchStatementAloneOrSingleline.java"),
                expected);
    }

    @Test
    public void testCaseBlocksInSwitchStatementAloneOrSingle2() throws Exception {
        final String[] expected = {
            "19:15: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 15),
            "28:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "40:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "43:15: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 15),
            "51:23: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 23),
            "72:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "81:23: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 23),
            "101:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyCaseBlocksInSwitchStatementAloneOrSingleline2.java"),
                expected);
    }

    @Test
    public void testCaseBlocksInSwitchStatementSame() throws Exception {
        final String[] expected = {
            "34:16: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 16),
            "45:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "74:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "79:51: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 51),
            "107:23: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 23),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyCaseBlocksInSwitchStatementSame.java"), expected);
    }

    @Test
    public void testCaseBlocksInSwitchStatementSame2() throws Exception {
        final String[] expected = {
            "19:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "28:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "40:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "43:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "51:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "71:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "78:34: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 34),
            "78:47: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 47),
            "86:23: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 23),
            "104:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyCaseBlocksInSwitchStatementSame2.java"), expected);
    }

    @Test
    public void testCaseBlocksWithSwitchRuleAlone() throws Exception {
        final String[] expected = {
            "33:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "45:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "46:27: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 27),
            "57:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "70:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "75:46: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 46),
            "84:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "84:36: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 36),
            "94:31: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 31),
            "95:31: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 31),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyCaseBlocksWithSwitchRuleAlone.java"),
                expected);
    }

    @Test
    public void testCaseBlocksWithSwitchRuleAloneOrSingleLine() throws Exception {

        final String[] expected = {
            "28:19: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 19),
            "42:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "54:23: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 23),
            "55:27: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 27),
            "65:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "78:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "83:46: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 46),
            "92:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "103:31: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 31),
        };
        final String fileName = "InputRightCurlyCaseBlocksWithSwitchRuleAloneOrSingleline.java";
        verifyWithInlineConfigParser(getPath(fileName), expected);
    }

    @Test
    public void testCaseBlocksWithSwitchExpressionAlone() throws Exception {
        final String[] expected = {
            "64:31: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 31),
            "87:42: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 42),
        };
        final String fileName = "InputRightCurlyCaseBlocksWithSwitchExpressionAlone.java";
        verifyWithInlineConfigParser(getPath(fileName), expected);
    }

    @Test
    public void testCaseBlocksWithSwitchExpressionAloneOrSingleLine() throws Exception {
        final String[] expected = {
            "64:31: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 31),
        };
        final String fileName =
                "InputRightCurlyCaseBlocksWithSwitchExpressionAloneOrSingleline.java";
        verifyWithInlineConfigParser(getPath(fileName), expected);
    }

    @Test
    public void testSwitchWhenGuards() throws Exception {
        final String[] expected = {
            "26:23: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 23),
            "37:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "52:27: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 27),
            "65:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "74:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
        };
        final String fileName = "InputRightCurlySwitchWhen.java";
        verifyWithInlineConfigParser(getNonCompilablePath(fileName), expected);
    }

    @Test
    public void testDefaultBlocksInSwitchStatementAlone() throws Exception {
        final String[] expected = {
            "34:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "45:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "74:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "79:68: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 68),
            "91:40: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 40),
            "98:43: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 43),
            "108:36: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 36),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyDefaultBlocksInSwitchStatementAlone.java"), expected);
    }

    @Test
    public void testDefaultBlocksInSwitchStatementAlone2() throws Exception {
        final String[] expected = {
            "18:15: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 15),
            "30:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "42:24: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 24),
            "54:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "65:25: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 25),
            "72:35: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 35),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyDefaultBlocksInSwitchStatementAlone2.java"), expected);
    }

    @Test
    public void testDefaultBlocksInSwitchStatementAloneOrSingleline() throws Exception {
        final String[] expected = {
            "34:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "45:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "74:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "79:74: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 74),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyDefaultBlocksInSwitchStatementAloneOrSingleline.java"),
                expected);
    }

    @Test
    public void testDefaultBlocksInSwitchStatementAloneOrSingleline2() throws Exception {
        final String[] expected = {
            "19:15: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 15),
            "31:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "44:15: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 15),
            "117:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyDefaultBlocksInSwitchStatementAloneOrSingleline2.java"),
                expected);
    }

    @Test
    public void testDefaultBlocksInSwitchStatementSame() throws Exception {
        final String[] expected = {
            "36:16: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 16),
            "47:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "76:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "81:74: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 74),
            "111:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyDefaultBlocksInSwitchStatementSame.java"), expected);
    }

    @Test
    public void testDefaultBlocksInSwitchStatementSame2() throws Exception {
        final String[] expected = {
            "19:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "31:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "43:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "55:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "85:35: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 35),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyDefaultBlocksInSwitchStatementSame2.java"), expected);
    }

    @Test
    public void testDefaultBlocksWithSwitchRuleAlone() throws Exception {
        final String[] expected = {
            "64:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "69:82: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 82),
            "79:35: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 35),
            "89:32: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 32),
        };
        verifyWithInlineConfigParser(
                getPath("InputRightCurlyDefaultBlocksWithSwitchRuleAlone.java"),
                expected);
    }

    @Test
    public void testDefaultBlocksWithSwitchRuleAloneOrSingleline() throws Exception {
        final String[] expected = {
            "56:27: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 27),
            "69:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "80:13: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 13),
            "85:70: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 70),
        };
        final String fileName =
                "InputRightCurlyDefaultBlocksWithSwitchRuleAloneOrSingleline.java";
        verifyWithInlineConfigParser(getPath(fileName), expected);
    }

    @Test
    public void testDefaultBlocksWithSwitchExpressionAlone() throws Exception {
        final String[] expected = {
            "63:31: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 31),
            "87:42: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 42),
            "113:34: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 34),
        };
        final String fileName =
                "InputRightCurlyDefaultBlocksWithSwitchExpressionAlone.java";
        verifyWithInlineConfigParser(getPath(fileName), expected);
    }

    @Test
    public void testDefaultBlocksWithSwitchExpressionAloneOrSingleline() throws Exception {
        final String[] expected = {
            "63:31: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 31),
            "114:34: " + getCheckMessage(MSG_KEY_LINE_ALONE, "}", 34),
        };
        final String fileName =
                "InputRightCurlyDefaultBlocksWithSwitchExpressionAloneOrSingleline.java";
        verifyWithInlineConfigParser(getPath(fileName), expected);
    }

    @Test
    public void testNonSingleLineMultiBlockStatement() throws Exception {
        final String[] expected = {
            "23:17: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 17),
            "28:22: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 22),
            "28:30: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 30),
            "36:9: " + getCheckMessage(MSG_KEY_LINE_SAME, "}", 9),
            "43:64: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 64),
            "43:75: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 75),
            "58:68: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 68),
            "58:79: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 79),
            "63:14: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 14),
            "63:37: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 37),
        };

        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestMultiBlockStatements.java"), expected
        );
    }

    @Test
    public void testNonSingleLineMultiBlockStatement2() throws Exception {
        final String[] expected = {
            "22:34: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 34),
            "22:57: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 57),
            "22:68: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 68),
            "33:27: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 27),
            "33:60: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 60),
            "33:74: " + getCheckMessage(MSG_KEY_LINE_BREAK_BEFORE, "}", 74),
        };

        verifyWithInlineConfigParser(
                getPath("InputRightCurlyTestMultiBlockStatements2.java"), expected
        );
    }
}
